name: Daily Weather Tracker

on:
  schedule:
    - cron: "0 7 * * *"   # Runs every day at 07:00 UTC
  workflow_dispatch:       # Allow manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run weather script
        run: python weather.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weather_log.json
          git commit -m "Weather update: $(date)"
          git push
